name: "PR Reviewer Slack Notify Action"
description: "Blow up a channel with @s when adding people to review your PR."
branding:
  color: blue
  icon: at-sign
inputs:
  aws-region:
    description: 'Region in which the Github <=> Slack engineer mapping JSON is stored'
    required: true
  aws-s3-bucket:
    description: 'Bucket in which the Github <=> Slack engineer mapping JSON object is stored in S3'
    required: true
  aws-s3-object-key:
    description: 'Name of the Github <=> Slack engineer mapping JSON object in S3'
    required: true
  base-branch:
    description: "Branch that you will be opening PRs in to (e.g. 'staging', 'master')."
    required: true
  bot-token:
    description: "OAuth token for your Slack App Bot to sign requests to Slack's API with."
    required: true
  channel-id:
    description: "ID of the channel or conversation in Slack you would like messages posted to."
    required: true
  github-token:
    description: "Personal access token with repository rights."
    required: true
  label-name-to-watch-for:
    description: "If you would like to notify the thread of a label being applied to a PR, set this."
    required: false
    default: ""
  ignore-draft-prs:
    description: "Do not message on draft PRs"
    required: false
    default: false
  silence-on-quiet-label:
    description: "Do not message if the PR has the `quiet` label"
    required: false
    default: false
  fail-silently:
    description: "Allow action to fail silently to hide the red X of death"
    required: false
    default: false
  verbose:
    description: "If verbose is set to true, the entire PR text is posted to Slack. If false, just the title is posted."
    required: false
    default: true
  
runs:
  using: "node20"
  main: "dist/index.js"
